// 자동생성 메세지를 기록하면 된다.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	mygroupexamplecomv1alpha1 "github.com/seoyhaein/myresource-crd/pkg/apis/mygroup.example.com/v1alpha1"
	scheme "github.com/seoyhaein/myresource-crd/pkg/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MyResourcesGetter has a method to return a MyResourceInterface.
// A group's client should implement this interface.
type MyResourcesGetter interface {
	MyResources(namespace string) MyResourceInterface
}

// MyResourceInterface has methods to work with MyResource resources.
type MyResourceInterface interface {
	Create(ctx context.Context, myResource *mygroupexamplecomv1alpha1.MyResource, opts v1.CreateOptions) (*mygroupexamplecomv1alpha1.MyResource, error)
	Update(ctx context.Context, myResource *mygroupexamplecomv1alpha1.MyResource, opts v1.UpdateOptions) (*mygroupexamplecomv1alpha1.MyResource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*mygroupexamplecomv1alpha1.MyResource, error)
	List(ctx context.Context, opts v1.ListOptions) (*mygroupexamplecomv1alpha1.MyResourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *mygroupexamplecomv1alpha1.MyResource, err error)
	MyResourceExpansion
}

// myResources implements MyResourceInterface
type myResources struct {
	*gentype.ClientWithList[*mygroupexamplecomv1alpha1.MyResource, *mygroupexamplecomv1alpha1.MyResourceList]
}

// newMyResources returns a MyResources
func newMyResources(c *MygroupV1alpha1Client, namespace string) *myResources {
	return &myResources{
		gentype.NewClientWithList[*mygroupexamplecomv1alpha1.MyResource, *mygroupexamplecomv1alpha1.MyResourceList](
			"myresources",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *mygroupexamplecomv1alpha1.MyResource { return &mygroupexamplecomv1alpha1.MyResource{} },
			func() *mygroupexamplecomv1alpha1.MyResourceList { return &mygroupexamplecomv1alpha1.MyResourceList{} },
		),
	}
}
