// 자동생성 메세지를 기록하면 된다.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/seoyhaein/myresource-crd/pkg/apis/mygroup.example.com/v1alpha1"
	mygroupexamplecomv1alpha1 "github.com/seoyhaein/myresource-crd/pkg/clientset/clientset/typed/mygroup.example.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMyResources implements MyResourceInterface
type fakeMyResources struct {
	*gentype.FakeClientWithList[*v1alpha1.MyResource, *v1alpha1.MyResourceList]
	Fake *FakeMygroupV1alpha1
}

func newFakeMyResources(fake *FakeMygroupV1alpha1, namespace string) mygroupexamplecomv1alpha1.MyResourceInterface {
	return &fakeMyResources{
		gentype.NewFakeClientWithList[*v1alpha1.MyResource, *v1alpha1.MyResourceList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("myresources"),
			v1alpha1.SchemeGroupVersion.WithKind("MyResource"),
			func() *v1alpha1.MyResource { return &v1alpha1.MyResource{} },
			func() *v1alpha1.MyResourceList { return &v1alpha1.MyResourceList{} },
			func(dst, src *v1alpha1.MyResourceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MyResourceList) []*v1alpha1.MyResource { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MyResourceList, items []*v1alpha1.MyResource) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
